apiVersion: tenantoperator.stakater.com/v1alpha1
kind: Template
metadata:
  name: docker-secret-template
parameters:
  - name: ENCRYPTED_DOCKER_CONFIG
    required: true
resources:
  manifests:
    - apiVersion: bitnami.com/v1alpha1
      kind: SealedSecret
      metadata:
        annotations:
          sealedsecrets.bitnami.com/cluster-wide: "true"
        creationTimestamp: null
        name: ${tenant}-docker-pull-secret
      spec:
        encryptedData:
          .dockerconfigjson: ${{ENCRYPTED_DOCKER_CONFIG}}
        template:
          data: null
          metadata:
            annotations:
              sealedsecrets.bitnami.com/cluster-wide: "true"
            creationTimestamp: null
            name: ${tenant}-docker-pull-secret
          type: kubernetes.io/dockerconfigjson
