apiVersion: tenantoperator.stakater.com/v1alpha1
kind: Template
metadata:
  name: secret-store-template
parameters:
  - name: ENCRYPTED_CLIENT_ID
    required: true
  - name: ENCRYPTED_CLIENT_SECRET
    required: true
  - name: AZURE_TENANT_ID
    required: true
resources:
  manifests:
    - apiVersion: bitnami.com/v1alpha1
      kind: SealedSecret
      metadata:
        annotations:
          sealedsecrets.bitnami.com/cluster-wide: "true"
        creationTimestamp: null
        name: keyvault-credentials
      spec:
        encryptedData:
          ClientID: ${{ENCRYPTED_CLIENT_ID}}
          ClientSecret: ${{ENCRYPTED_CLIENT_SECRET}}
        template:
          data: null
          metadata:
            annotations:
              sealedsecrets.bitnami.com/cluster-wide: "true"
            creationTimestamp: null
            name: keyvault-credentials
          type: Opaque
    - apiVersion: external-secrets.io/v1alpha1
      kind: SecretStore
      metadata:
        name: ${namespace}-secret-store
      spec:
        provider:
          azurekv:
            authSecretRef:
              clientId:
                key: ClientID
                name: keyvault-credentials
              clientSecret:
                key: ClientSecret
                name: keyvault-credentials
            authType: ServicePrincipal
            tenantId: ${{AZURE_TENANT_ID}}
            vaultUrl: https://${namespace}.vault.azure.net
