apiVersion: tenantoperator.stakater.com/v1beta1
kind: Tenant
metadata:
  name: mattermost
spec:
  quota: nordmart-medium
  owners:
    users:
      - rasheed@stakater.com
      - faizan@stakater.com
  commonMetadata:
    annotations:
      openshift.io/node-selector: node-role.kubernetes.io/infra=
  namespaces:
  - system
  - instance
